server.port=7777
server.name=Ssaulabirun
server.maxPlayers=1000
db.url=jdbc:h2:./data/ssaulabirun
db.user=ssaulabirun
db.password=ssaulabirun2024
world.startMapId=1
world.startX=100
world.startY=100
server.version=1.0.0
